package SoccerApp.utility.enums;

public enum EMacStatu {
	// referans noktası ev sahibi ör:   KONUM_TOPKIMDE
	KALE_DEPLASMAN, KALE_EVSAHIBI,
	DEFANS_DEPLASMAN, DEFANS_EVSAHIBI,
	ORTASAHA_DEPLASMAN, ORTASAHA_EVSAHIBI,
	FORVET_DEPLASMAN, FORVET_EVSAHIBI,
	DEPKALE_DEPLASMAN, DEPKALE_EVSAHIBI
}